baseURL = 'https://deeplearn.ltd/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = ''
theme = 'ananke'
SectionPagesMenu = "main"
pagination.pagerSize = 5
googleAnalytics = "G-D8VY8VWJDC"
enableRobotsTXT = true
omit_header_text = true
copyright = 'DeepLearn LTD'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
site_logo = "logo2.png"
favicon = 'favicon2.png'
description = 'DeepLearn Research & Development'

[params.social]
name = "github"
url = "https://github.com/Deeplearn-PeD/"
label = "Our Github Organization"


[languages.en]
title = 'DeepLearn Research & Development'
languageName = 'English'
weight = 1

[languages.pt]
title = 'DeepLearn Pesquisa e Desenvolvimento'
languageName = 'Portuguese'
weight = 2
